< [Online Version Python Data Science Handbook](https://github.com/jakevdp/PythonDataScienceHandbook)| [Menu](https://)>
# 3. Data Manipulation with Pandas 
* Pandas is a newer package built on top of NumPy, and provides an efficient implementation of a DataFrame.
* In this chapter, we will focus on the mechanics of using **Series**, **DataFrame**, and related structures effectively
* More detailed documentation, along with tutorials and other resources, can be found at http://pandas.pydata.org/.

## Data Indexing and Selection
* Data Selection in Series
* Data Selection in DataFrame

### Data Selection in Series

In [1]:
import pandas as pd

class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args
        
    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                         for a in self.args)
    
    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)

In [5]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
    index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [6]:
data['b']

0.5

In [7]:
'a' in data

True

In [8]:
data.index
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [9]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [10]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [11]:
# Select all values as array
data.values

array([0.25, 0.5 , 0.75, 1.  , 1.25])

In [12]:
# Select rows by python index or explicit index from-to
data[0] 
data[0:3] 
data.loc['a':'c']
data.iloc[0:3]

a    0.25
b    0.50
c    0.75
dtype: float64

In [13]:
# Select rows by explicit index
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

In [14]:
# Select rows by value
data[(data > 0.3) & (data < 0.8)] 

b    0.50
c    0.75
dtype: float64

In [15]:
# Select row value by python index or explicit index
data['c']
data.loc['c']
data.iloc[2]

0.75

# DATAFRAME

In [5]:
population_dict = {'California': 38332521,
    'Texas': 26448193,
    'New York': 19651127,
    'Florida': 19552860,
    'Illinois': 12882135}
population = pd.Series(population_dict)
area_dict = {'California': 423967, 
    'Texas': 695662, 
    'New York': 141297,
    'Florida': 170312, 
    'Illinois': 149995}
area = pd.Series(area_dict)
df = pd.DataFrame({'population': population,
    'area': area})
df

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [7]:
# Select all values as array
df.values

array([[38332521,   423967],
       [26448193,   695662],
       [19651127,   141297],
       [19552860,   170312],
       [12882135,   149995]])

In [8]:
# Select rows by python index from-to > array
df.values[0]
df.values[0:3]

array([[38332521,   423967],
       [26448193,   695662],
       [19651127,   141297]])

### ITERATE OVER ROWS

In [9]:
for index, row in df.iterrows():
    print(index, row['population'], row['area'])

California 38332521 423967
Texas 26448193 695662
New York 19651127 141297
Florida 19552860 170312
Illinois 12882135 149995


### FILTER BY COLUMN

In [10]:
# one column > SELECT area FROM df;
df.area.to_frame()
df['area'].to_frame()
df[['area']]

# 2 o more columns > SELECT population, area FROM df;
df[['population','area']]
df.loc[:, :'area']
df.loc[:, 'population':'area']
df.loc[:, ['population','area']]
df.iloc[:, :2]
df.iloc[:, 0:2]
df.iloc[:, [0,1]]

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

### FILTER BY ROW

In [68]:
# all columns > SELECT * FROM df LIMIT 3;
df[:3]
df[0:3]
df[:'New York']
df['California':'New York']
states.loc[:'New York']
states.loc['California':'New York']
states.loc[['California','Texas','New York']]
states.iloc[:3]
states.iloc[0:3]
states.iloc[[1,2,3]]
states.iloc[:3, :]

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297

In [73]:
# filter by columns
df.loc[:'New York', :'area']
df.loc['California':'New York', 'population':'area']
df.loc[['California','Texas','New York'], ['population','area']]
df.iloc[:3, :2]
df.iloc[0:3, 0:2]
df.iloc[[0,1,2], [0,1]]

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297

## Columns

### Columns > cast

In [11]:
#https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html
#https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.astype.html
# by date > 
#     df = df.astype({'date': 'datetime64', 'to_date': 'datetime64'})
#     df = df.astype({'date': 'datetime64[ns]'})
#     df['date'] = df['date'].astype('datetime64[ns]')
#     df['date'] = pd.to_datetime(df["date"])
#     df['date'] = pd.to_datetime(df['date']).dt.strftime('%Y-%m-%d %H:%M:%S') > str
#     df['date'] = pd.to_datetime(pd.to_datetime(df['date']).dt.strftime('%Y-%m-%d %H:%M:%S')) > datetime
df[df.columns[0]].dtypes
df.dtypes 

population    int64
area          int64
dtype: object

### Columns > add / modify 

In [12]:
# ADD COLUMN > SELECT (Expression) AS <column> ...
# MODIFY COLUMN > UPDATE <column> = (Expression) ...
# by date > 
#     df['field'] = df['date'].dt.weekday
#     df['field'] = df['date'].dt.strftime('%Y-%m-%d') > str
#     df['field'] = df['date'].dt.total_seconds()
# by string
#     df['field'] = df['str'].str.upper()
#     df['field'] = df['str'].str.replace('a', 'A', regex=False)
# by string regular expressions
#     df['field'] = df['str'].str.extract(r'(^w{5})')
#     df['field'] = df['str'].str.extract(r'(^Analytics-(access|delete))')
#     df['field'] = df['str'].str.replace('Chapman|Jones', 'Salamo', regex=True)
# by lambda
#     df['field'] = df['lambda'].apply(lambda x: str(x).upper()) 
# by cut
#     df['field'] = pd.cut(df['cut'], [0, 100, 200])
df['density'] = df['population'] / df['area']
df

population    area     density
California    38332521  423967   90.413926
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763

In [12]:
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.cut.html
# crea contenedores donde frecuencia de las muestras es desigual en cada contenedor

# Use cut when you need to segment and sort data values into bins   

df['density_range'] = pd.cut(df['density'], [0, 100, 200]);df

population    area     density density_range
California    38332521  423967   90.413926      (0, 100]
Texas         26448193  695662   38.018740      (0, 100]
New York      19651127  141297  139.076746    (100, 200]
Florida       19552860  170312  114.806121    (100, 200]
Illinois      12882135  149995   85.883763      (0, 100]

In [22]:
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.qcut.htm
# crea contenedores de tamaño desigual pero la frecuencia de las muestras es igual en cada contenedor (basadas en cuantiles de muestra)
df['density_range'] = pd.qcut(df['density'], 4)
display('df', 'df["density"].describe().to_frame()')

df
            population    area     density       density_range
California    38332521  423967   90.413926    (85.884, 90.414]
Texas         26448193  695662   38.018740    (38.018, 85.884]
New York      19651127  141297  139.076746  (114.806, 139.077]
Florida       19552860  170312  114.806121   (90.414, 114.806]
Illinois      12882135  149995   85.883763    (38.018, 85.884]

df["density"].describe().to_frame()
          density
count    5.000000
mean    93.639859
std     37.672251
min     38.018740
25%     85.883763
50%     90.413926
75%    114.806121
max    139.076746

### Columns > filter

In [14]:
# FILTER COLUMN > SELECT ... WHERE <column> = <condition>
# by conditional
#    & (AND), | (OR), >= (MAJOR OR EQUAL), >= (MINOR OR EQUAL), == (EQUAL), != (NOT EQUAL)
#    df[(df["field"] == "XXX") | (df["field"] == "YYY")] 
# by negative conditional
#    df[~df["field"].str.endswith('XXX')]
# by date > 
#    df.loc[df['field'] >= '2021-03-05'] 
#    df.loc[df['field'].dt.weekday == 2] 
#    df[df['field'].dt.strftime('%Y-%m-%d') = '2021-03-05'] 
#    df[df['field'].dt.total_seconds() >= 12345] 
# by string
#    df[df["field"].str.startswith('XXX')] 
#    df[df["field"].str.endswith('XXX')]
#    df[df["field"].str.contains('XXX', regex=False)] 
#    df[df["field"].str.len() != 10] 
#    df[df["field"].astype(str).str.len() != 10] 
#    df[df["field"].isin(["XXX", "YYY"])]
# by string regular expressions
#    df[df['field'].str.match('^P.*') == True]
#    df[df["field"].str.contains('XXX|YYY', regex=True)] 
# by lambda
#    df[df["field"].apply(lambda x: len(str(x)) != 10] 
df[(df.density > 90) & (df.density < 140)]
df.loc[(df.density > 90) & (df.density < 140)]
df.loc[(df.density > 90) & (df.density < 140), :]
df.loc[(df.density > 90) & (df.density < 140), :'density']
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html
df.query('density > 90 and density < 140')

population    area     density
California    38332521  423967   90.413926
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121

In [16]:
# MODIFY BY ROWS & COLUMNS
#      SQL > UPDATE density = 90 FROM states WHERE <condition> > pandas.core.frame.DataFrame
df.iloc[0, 2] = 90
df.at['California','density'] = 90
df.loc['California', 'density'] = 90
df.loc[df["density"] == 90, 'density'] = 90
df

population    area     density
California    38332521  423967   90.000000
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763

In [17]:
# CONVERT COLUMN(by python index) > SELECT CAST(area) > pandas.core.series.Series
# TIMESTAMP
# https://pandas.pydata.org/docs/reference/api/pandas.Timestamp.html
from datetime import datetime

# states['date'] = pd.date_range(start='01/01/2021', periods=len(states), freq='D') # > datetime64[ns]
# states['dates'] = pd.to_datetime("01/01/2021") # > datetime64[ns]
# states['dates'] = pd.Timestamp("01/01/2021") # > datetime64[ns]

# df['timestamp'] = pd.to_datetime(df['timestamp'], format='%Y-%m-%d')
#states['timestamp'] = dt.datetime.now()
dt.datetime.now()
pd.to_datetime('now')
datetime.datetime.utcnow().replace(microsecond=0)
datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
df['date_of_birth'] = pd.to_datetime(df['date_of_birth'],format='%d/%m/%Y')

# Convert the date to datetime64 
# df['timestamp'] = pd.to_datetime(df['timestamp'], format='%Y-%m-%d')
# How to manipulate textual data
# df[df["process_timestamp"].dt.strftime('%Y-%m-%d') == '2021-03-16']

df['dates'] = datetime.date(2030, 2, 2)
df
df.dtypes

NameError: name 'dt' is not defined

In [18]:
# Pivot table
df.T

California         Texas      New York       Florida      Illinois
population  38332521.0  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
area          423967.0  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
density           90.0  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

## GROUP BY

In [28]:
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.groupby.DataFrameGroupBy.aggregate.html

In [ ]:
a = df.groupby(["action","status"])
df.groupby(["action","status"]).groups
df.groupby(["action","status"]).groups.keys()
df.groupby(["action","status"]).count()
df.groupby(["action"])['status'].count()
df.groupby(["action"])['status'].value_counts()
df.groupby(["action","status"])['jobId'].agg(['count'])
df.groupby(["action"])['status'].agg(['count'])
df.groupby(["action","status"]).agg({'jobId': 'count'})
df.groupby(["action","status"]).agg({'diffDateSeconds': ['min', 'max', 'mean']})

d = df.groupby(["action","status"]).agg({'jobId': 'count', 'diffDateSeconds': ['min', 'max', 'mean']})

## MERGING

In [13]:
# https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html
df1 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2"],
        "B": ["B0", "B1", "B2"],
        "C": ["C0", "C1", "C2"]
    },
    index=[0, 1, 2],
)
df2 = pd.DataFrame(
    {
        "A": ["A3", "A4", "A5"],
        "B": ["B3", "B4", "B5"],
        "C": ["C3", "C4", "C5"]
    },
    index=[0, 1, 2],
)

In [14]:
pd.concat([df1, df2])

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [18]:
# Ignoring the index
pd.concat([df1, df2], ignore_index=True)

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3
4  A4  B4  C4
5  A5  B5  C5

In [25]:
# Adding MultiIndex keys
df = pd.concat([df1, df2], keys=["df1", "df2"]); df

A   B   C
df1 0  A0  B0  C0
    1  A1  B1  C1
    2  A2  B2  C2
df2 0  A3  B3  C3
    1  A4  B4  C4
    2  A5  B5  C5

In [26]:
# Select by Key
df.loc["df2"]

A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

## ORDER BY

In [1]:
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html
#     result.sort_values(by=['col1', 'col2']) > multiple columns
#     result.sort_values(by='col1', ascending=False) > Sort Descending

In [4]:
df = pd.DataFrame({
    'col1': ['A', 'A', 'B', np.nan, 'D', 'C'],
    'col2': [2, 1, 9, 8, 7, 4]
})
df

NameError: name 'np' is not defined